AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Creating all the related resources to generate a State Of DevOps dashboard'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mechanicalrock-state-of-devops-dashboard
    Description: Creating State of DevOps dashboard based on cloudwatch alarms and metrics.
    Author: Mechanical Rock
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['stateofdevops', 'dashboard', 'sdo', 'service-health', 'monitoring','mttr', 'mtbf']
    HomePageUrl: https://github.com/MechanicalRock/aws-stateofdevops-dashboard
    SemanticVersion: 1.0.8
    SourceCodeUrl: https://github.com/MechanicalRock/aws-stateofdevops-dashboard

Parameters:
  PermissionsBoundary:
    Description: "An optional permissions boundary to apply to all roles"
    Type: String
    ConstraintDescription: Must match a valid ARN of an IAM policy for the permission boundary
    AllowedPattern: "^$|arn:aws:iam::\\d{12}:policy/[a-zA-Z\\-]+$"
    Default: ""
  SanitisePattern:
    Description: 'comma delimited list of patterns to use to sanitise pipeline names.  Strips the pipeline name to characters before the matching patter.  Example pipeline with name "foo-pipeline123" and sanitise pattern "-pipeline" will be reported as "foo"'
    Type: String
    Default: "-pipeline"
    AllowedPattern: '[a-zA-Z_\\-]+(,[a-zA-Z_\\-]+)*'

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 60
    Handler: index.handler
    MemorySize: 128
    Tracing: Active

Conditions:
  HasPermissionBoundary: !Not [!Equals [!Ref PermissionsBoundary, ""]]

Resources:

  SDOAppNames:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/state-of-devops/app-names"
      Type: StringList
      Value: "sod-default-app-name"
      Description: comma separated list of app names deployed in your aws account

  DescribeAlarmPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: cloudwatch:DescribeAlarmHistory
            Resource: '*'

  ListPipelinePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: codepipeline:ListPipelines
            Resource: '*'

  DynamoStream:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TABLE_NAME: !Ref EventStoreDynamoTable
      ReservedConcurrentExecutions: 1
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - EventStoreDynamoTable
                - StreamArn
            StartingPosition: TRIM_HORIZON
      CodeUri: ./src/dynamoStream
      Timeout: 60
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref EventStoreDynamoTable
      PermissionsBoundary:
        !If [HasPermissionBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]

  ServiceHealthAlarmGenerator:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 */12 * * ? *)
      CodeUri: src/ServiceHealthAlarmGenerator
      Timeout: 300
      Policies:
        - Statement:
            - Effect: Allow
              Action: 
                - cloudwatch:DescribeAlarms
                - cloudwatch:PutMetricAlarm
              Resource: "*"
            - Effect: Allow
              Action: 
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/state-of-devops/app-names"
      PermissionsBoundary:
        !If [HasPermissionBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]

  StateOfDevOpsTrendGenerator:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          SANITISE_PATTERNS: !Ref SanitisePattern
          TABLE_NAME: !Ref EventStoreDynamoTable
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/5 * * * ? *)
      CodeUri: src/StateOfDevopsDashboard
      Timeout: 60
      Policies:
        - Statement:
            - Effect: Allow
              Action: 
                - cloudwatch:GetDashboard
                - cloudwatch:ListDashboards
                - cloudwatch:PutDashboard
                - codepipeline:ListPipelines
              Resource: "*"
      PermissionsBoundary:
        !If [HasPermissionBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]

  StateChangeHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Capturing all cloudwatch alarm State changes in dynamo
      Runtime: nodejs12.x
      CodeUri: ./src/StateChangeHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref EventStoreDynamoTable
          SANITISE_PATTERNS: !Ref SanitisePattern
      Events:
        cloudwatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - 'aws.cloudwatch'
              detail-type:
                - 'CloudWatch Alarm State Change'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventStoreDynamoTable
        - !Ref ListPipelinePolicy
        - !Ref DescribeAlarmPolicy
      PermissionsBoundary:
        !If [HasPermissionBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]

        
  EventStoreDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'resourceId'
          AttributeType: 'S'
        - AttributeName: 'pipelineName'
          AttributeType: 'S'
        - AttributeName: 'bookmarked'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: HASH
        - AttributeName: 'resourceId'
          KeyType: 'RANGE'
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: 'resourceId-id-index'
          KeySchema:
            - AttributeName: 'resourceId'
              KeyType: HASH
            - AttributeName: 'id'
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'
        - IndexName: 'pipelineName-index'
          KeySchema:
            - AttributeName: 'pipelineName'
              KeyType: HASH
            - AttributeName: 'bookmarked'
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'
